name: CI Tests

on:
  push:
    branches:
      - main
      - add-ci-workflow
  pull_request:
    branches:
      - main

jobs:
  test:
    name: CI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests and coverage
        run: |
          coverage run -m pytest
          coverage report
